---
title: "ChocoRatings"
author: "Jeff Grayum"
date: "1/22/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Installing Libraries.
```{r}
library(tidyverse)
library(scales)
library(janitor)
library(tidytuesdayR)
library(ggthemes)
library(silgelib)
library(tidytext)
library(tidymodels)
library(textrecipes)
theme_set(theme_hc())
```

Importing data.
```{r}
tuesdata <- tidytuesdayR::tt_load('2022-01-18')

chocolate <- tuesdata$chocolate

chocolate %>%
  view()
```

We will try and predict "rating" based on "most memorable characteristics"

Exploratoray data analysis.
```{r}

chocolate %>%
  ggplot(aes(rating)) +
  geom_histogram(bins = 15) +
  labs(x = "Rating",
       y = "",
       title = "Chocolate Ratings") 

tidy_chocolate <- chocolate %>%
  unnest_tokens(word, most_memorable_characteristics) %>%
  view()

tidy_chocolate %>%
  count(word, sort = TRUE)
```

Exploratory data analysis cont.
```{r}
tidy_chocolate %>%
  group_by(word) %>%
  summarize(n = n(),
            rating = mean(rating)) %>%
  ggplot(aes(n, rating)) +
  geom_hline(yintercept = mean(chocolate$rating),
                               lty = 2, color = "gray50", size = 1) +
  geom_point(color = "midnightblue", alpha = 0.7) +
  geom_text(aes(label = word), check_overlap = TRUE,
            vjust = "top", hjust = "left") +
  scale_x_log10() +
  labs(x = "Popularity (log scale)",
       y = "Rating")
```

We will now begin our modeling!
```{r}
set.seed(123)

#Process: Split, train split, test split.

#Split data is what we use to train, test, and tune.  Must consider "data budget"!
choco_split <- initial_split(chocolate, strata = rating)

choco_train <- training(choco_split)

choco_test <- testing (choco_split)

#Now create re-sampling folds from the training set (simulated versions of training set...using crossvalidation to create folds)  All from training set!
set.seed(234)
choco_folds <- vfold_cv(choco_train, strata = rating)
choco_folds
```

Let's set up our preprocessing using a recipe.
```{r}
choco_recipe <- 
  recipe(rating ~ most_memorable_characteristics, data = choco_train) %>%
  step_tokenize(most_memorable_characteristics) %>%
  step_tokenfilter(most_memorable_characteristics, max_tokens = 100) %>%
  step_tf(most_memorable_characteristics)
```

